openapi: 3.0.0
info:
  title: comapny-info
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /company:
    post:
      tags:
        - default
      summary: post company
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ""
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: get company
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
